print("Thay đổi để nghịch code")
print("Thay đổi để nghịch code")
print("Thay đổi để nghịch code")
print("Thay đổi để nghịch code")
print("lalalalalalallalalalalala")
print("hahahahahahahahhahahahahha")